{% set version = "4.8.11" %}

package:
  name: sourmash-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-{{ version }}.tar.gz
  sha256: 1a06a76df464b92685779aaaa6ed02a577bdd73a4ab32972e8134581034d34bf

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 1
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  skip: true  # [py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }} >=1.65.0
    - maturin
    - cargo-bundle-licenses
    - libclang                            # [unix]
    - clangdev                            # [unix]
    - xz
  host:
    - python
    - pip
    - maturin
    - toml
    - cffi

  run:
    - python
    - screed >=1.1.2
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy
    - bitstring >=3.1.9,<4
    - libstdcxx-ng                        # [linux]
    - libgcc-ng                           # [linux]
    # Due to rocksDB: https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/sourmash-bio/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/sourmash-bio/sourmash
  doc_url: https://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
    - bluegenes
