{% set version = "4.7.0" %}

package:
  name: sourmash-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-{{ version }}.tar.gz
  sha256: 4135ac82059da24a30f3b9554ecd0107dbf68eac2828f39fa275038554b76311

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 0
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  skip: true  # [py<38]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('m2w64_c') }}           # [win]
    - {{ compiler('rust') }} >=1.56.1
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - toml
    - cffi

  run:
    - python
    - screed >=1.1.2
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy
    - bitstring >=3.1.9,<4
    - importlib_metadata                  # [py<310]

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/sourmash-bio/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/sourmash-bio/sourmash
  doc_url: https://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
    - bluegenes
