{% set version = "4.3.0" %}

package:
  name: sourmash-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-{{ version }}.tar.gz
  sha256: 49beab779e62dbea6cfde6182f6d90a76cf1bf3fe13f58eac872aec73496338b

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 2
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - rust >=1.48.0
  host:
    - python
    - pip
    - setuptools >=48,<60
    - milksnake
    - setuptools_scm >=4,<6
    - setuptools_scm_git_archive

  run:
    - python
    - setuptools
    - screed >=1.0.5
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/sourmash-bio/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/sourmash-bio/sourmash
  doc_url: https://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
    - bluegenes
