context:
  version: 4.8.12

package:
  name: sourmash-minimal
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-${{ version }}.tar.gz
  sha256: 33fd19fb2570a03c4dd7048cd32aaead497600a0080cd655e67bd1cbc6f00524

build:
  number: 0
  skip:
    - match(python, "<3.10")
  python:
    entry_points:
      - sourmash = sourmash.__main__:main
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then: /usr/lib/libresolv.9.dylib

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }} >=1.65.0
    - maturin
    - cargo-bundle-licenses
    - xz

    # cross-compilation dependencies
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - cffi

    - if: unix
      then:
        - libclang
        - clangdev

  host:
    - python
    - pip
    - maturin
    - toml
    - cffi

  run:
    - python
    - screed >=1.1.2
    - cffi >=1.17.1
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy
    - bitstring >=3.1.9,<4

tests:
  - python:
      imports:
        - sourmash
      pip_check: false
  - script:
      - sourmash --help
      - sourmash info

about:
  summary: Compute and compare MinHash signatures for DNA data sets.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/sourmash-bio/sourmash
  repository: https://github.com/sourmash-bio/sourmash
  documentation: https://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
    - bluegenes
